### ISSUE TITLE
Cannot run development instance

### ISSUE THREAD

**Issue by yukinchan** [ryncsn/metadash#15] opened 2018-11-01 02:43 UTC
`npm run ui-dev` returns a single error without any details.

>  ERROR  Failed to compile with 1 errors
> 
>  error

`./bin/ui-server` runs but seems some files are missing.

> $ ./bin/ui-server
> [HPM] Proxy created: /api  ->  http://localhost:5000
> [HPM] Proxy created: /docs  ->  http://localhost:5000
> Server Started
> 127.0.0.1 - GET /__webpack_hmr HTTP/1.0 404 269 - 9.302 ms
> Error: ENOENT: no such file or directory, stat 'metadash/metadash/dist/index.html'
>     at Error (native)
>

**Comment by waynesun09** [comment] 2018-11-06 03:21
The issue is not fixed yet, still on figuring out local dev with http-proxy-middleware config

**Comment by ryncsn** [comment] 2018-11-06 12:37
Fixed in commit 4e741569810bb1b37e49ee9a8f4f6758b9e65e60, thanks for the report :smile:

**Comment by ryncsn** [comment] 2018-11-06 12:38
And btw ./bin/ui-server is intend to be used for serving asserts with higher concurrency, not for development.

**Closed as completed by ryncsn** 2018-11-06 12:38 UTC
